version: '3.8'

services:
  app:
    build: .
    container_name: object_tracking

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all  
              capabilities: [gpu]
  
    environment:  
      - NVIDIA_VISIBLE_DEVICES=all
    
    volumes:
      - .:/app
      - ./datasets:/app/datasets
      - ./runs:/app/runs
      - ./videos:/app/videos
  